config/routes.rb
Rails.application.routes.draw do

  

  resources :my_users
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/home',  to: 'users#home'
  get '/about', to: 'users#about'
  root 'users#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_user.rb
class MyUser < ApplicationRecord
  has_secure_password
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      else
        @current_user = nil
      end
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
  end
end

app/controllers/my_users_controller.rb
class MyUsersController < ApplicationController
  before_action :set_my_user, only: [:show, :edit, :update, :destroy]

  # GET /my_users
  # GET /my_users.json
  def index
    @my_users = MyUser.all
  end

  # GET /my_users/1
  # GET /my_users/1.json
  def show
  end

  # GET /my_users/new
  def new
    @my_user = MyUser.new
  end

  # GET /my_users/1/edit
  def edit
  end

  # POST /my_users
  # POST /my_users.json
  def create
    @my_user = MyUser.new(my_user_params)

    respond_to do |format|
      if @my_user.save
        format.html { redirect_to @my_user, notice: 'My user was successfully created.' }
        format.json { render :show, status: :created, location: @my_user }
      else
        format.html { render :new }
        format.json { render json: @my_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_users/1
  # PATCH/PUT /my_users/1.json
  def update
    respond_to do |format|
      if @my_user.update(my_user_params)
        format.html { redirect_to @my_user, notice: 'My user was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_user }
      else
        format.html { render :edit }
        format.json { render json: @my_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_users/1
  # DELETE /my_users/1.json
  def destroy
    @my_user.destroy
    respond_to do |format|
      format.html { redirect_to my_users_url, notice: 'My user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_user
      @my_user = MyUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_user_params
      params.require(:my_user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_users_helper.rb
module MyUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/login.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
<p id="notice"><%= notice %></p>
<h1>Example</h1>
<p>Lorem ipsum …</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Preorder24</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="css/welcome.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/my_users/_form.html.haml
= form_for @my_user do |f|
  - if @my_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@my_user.errors.count, "error")} prohibited this my_user from being saved:"
      %ul
        - @my_user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/my_users/edit.html.haml
%h1 Editing my_user

= render 'form'

= link_to 'Show', @my_user
\|
= link_to 'Back', my_users_path

app/views/my_users/index.html.haml
%h1 Register Page

%table
  %thead
    %tr
      %th Email (Username)
      %th 
      %th
      %th
      %th

  %tbody
    - @my_users.each do |my_user|
      %tr
        %td= my_user.email
        %td= my_user.password
        %td= link_to 'Show', my_user
        %td= link_to 'Edit', edit_my_user_path(my_user)
        %td= link_to 'Destroy', my_user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New My user', new_my_user_path

app/views/my_users/new.html.haml
%h1 Register

= render 'form'

= link_to 'Back', my_users_path

app/views/my_users/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @my_user.email
%p
  %b Password:
  = @my_user.password

= link_to 'Edit', edit_my_user_path(@my_user)
\|
= link_to 'Back', my_users_path

app/views/users/_edit_form.html.erb
<div class="container">
    <header class="site-header">
        <image src="/images/logo.png" width="350" height="100">
            <nav>
            <span class="menu">
            <ul>
                <li><a><%= link_to "Home" , home_path %> </a></li>
                <% if current_user %>
                    
                    
                <% else %>
                    <li><a><%= link_to "Sign Up", signup_path %></li></a>
                    <li><a><%= link_to "Log In", login_path %></li></a>
                <% end %>
                <li><a><%= link_to "About" , about_path %></a></li>
                
                <% if current_user %>
                    <li><a><%= link_to "Log Out", logout_path %></li></a>
                    <li><a><%= link_to "Edit", edit_user_path(current_user) %></li></a>
                    Logged in as <%= current_user.email %>.
                    
                <% end %>
            </ul>
        </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
        <%= form_with(model: user, local: true) do |form| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        
              <ul>
                <% user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        
          <h1>Editing User</h1>
          <div class="field">
            <%= form.label :email %>
            <%= form.text_field :email %>
          </div>
        
          <div class="field">
            <%= form.label :password %>
            <%= form.password_field :password %>
          </div>
        
          <div class="field">
            <%= form.label :Password_Confirmation %>
            <%= form.password_field :Password_Confirmation %>
          </div>
        
          <div class="actions">
            <%=  form.submit %>
          </div>
        <% end %>
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>

app/views/users/_form.html.erb
<div class="container">
    <header class="site-header">
        <image src="images/logo.png" width="350" height="100">
            <nav>
            <span class="menu">
            <ul>
                <li><a><%= link_to "Home" , home_path %> </a></li>
                <% if current_user %>
                    
                    
                <% else %>
                    <li><a><%= link_to "Sign Up", signup_path %></li></a>
                    <li><a><%= link_to "Log In", login_path %></li></a>
                <% end %>
                <li><a><%= link_to "About" , about_path %></a></li>
                
                <% if current_user %>
                    <li><a><%= link_to "Log Out", logout_path %></li></a>
                    <li><a><%= link_to "Edit", edit_user_path(current_user) %></li></a>
                    Logged in as <%= current_user.email %>.
                    
                <% end %>
            </ul>
        </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
        <%= form_with(model: user, local: true) do |form| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
        
              <ul>
                <% user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        
          <h1>Register</h1>
          <div class="field">
            <%= form.label :email %>
            <%= form.text_field :email %>
          </div>
        
          <div class="field">
            <%= form.label :password %>
            <%= form.password_field :password %>
          </div>
        
          <div class="field">
            <%= form.label :Password_Confirmation %>
            <%= form.password_field :Password_Confirmation %>
          </div>
        
          <div class="actions">
            <%=  form.submit %>
          </div>
        <% end %>
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>

app/views/users/about.html.erb
<div class="container">
    <header class="site-header">
        <image src="images/logo.png" width="350" height="100">
            <nav>
            <span class="menu">
                    <ul>
                        <li><a><%= link_to "Home" , home_path %> </a></li>
                        <% if current_user %>
                            
                            
                        <% else %>
                            <li><a><%= link_to "Sign Up", signup_path %></li></a>
                            <li><a><%= link_to "Log In", login_path %></li></a>
                        <% end %>
                        <li><a><%= link_to "About" , about_path %></a></li>
                        
                        <% if current_user %>
                            <li><a><%= link_to "Log Out", logout_path %></li></a>
                            <li><a><%= link_to "Edit", edit_user_path(current_user) %></li></a>
                            Logged in as <%= current_user.email %>.
                            
                        <% end %>
                    </ul>
                </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Team Member</p>
            </header>
            <article>
                <p style="text-align: center;"><b>Auttaphol Thongvicit 5810613256</b></p>
                <p style="text-align: center;"><b>Tuchdech Jirabunyadech 5910613248</b></p>
                <p style="text-align: center;"><b>Boonyanut Puingyamsual 5910613305</b></p>
                <p style="text-align: center;"><b>Kittikun Kittithammo 5910613321</b></p>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Proposal</p>
            </header>
            <article>
                <center>
                    <table cellspacing="20">
                        <tr>
                            <td><img src="images/pro1.png" width="350px" height="350px"></td>
                            <td><img src="images/pro2.png" width="350px" height="350px"></td>
                        </tr>
                        <tr>
                            <td><img src="images/pro3.png" width="350px" height="350px"></td>
                            <td><img src="images/pro4.png" width="350px" height="350px"></td>
                        </tr>
                    </table>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">User Stories</p>
            </header>
            <article>
                <img src="images/story1.png" width="500px" height="400px">
                <img src="images/story2.png" width="500px" height="400px">
                <img src="images/story3.png" width="500px" height="400px">
                <img src="images/story4.png" width="500px" height="400px">
                <img src="images/story5.png" width="500px" height="400px">
                <img src="images/story6.png" width="500px" height="400px">
                <img src="images/story7.png" width="500px" height="400px">
                <img src="images/story8.png" width="500px" height="400px">
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Gitlab Repository Link</p>
            </header>
            <article>
                <center>
                    <p style="font-size: 1.2em"><a href="https://gitlab.com/5910613248/24preorder.git">https://gitlab.com/5910613248/24preorder.git</a></p>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Pivotal Tracker Link</p>
            </header>
            <article>
                <center>
                    <p style="font-size: 1.2em"><a href="https://www.pivotaltracker.com/projects/2407283">https://www.pivotaltracker.com/projects/2407283</a></p>
                </center>
            </article>
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>

app/views/users/edit.html.erb
<%= render 'edit_form', user: @user %>

app/views/users/home.html.erb
<div class="container">
    <header class="site-header">
        <image src="images/logo.png" width="350" height="100">
            <nav>
                <span class="menu">
                    <ul>
                        <li><a><%= link_to "Home" , home_path %> </a></li>
                        <% if current_user %>
                            
                            
                        <% else %>
                            <li><a><%= link_to "Sign Up", signup_path %></li></a>
                            <li><a><%= link_to "Log In", login_path %></li></a>
                        <% end %>
                        <li><a><%= link_to "About" , about_path %></a></li>
                        
                        <% if current_user %>
                            <li><a><%= link_to "Log Out", logout_path %></li></a>
                            <li><a><%= link_to "Edit", edit_user_path(current_user) %></li></a>
                            Logged in as <%= current_user.email %>.
                            
                        <% end %>
                    </ul>
                </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
            <img src="images/maintain.jpg" style="padding-top:100px;padding-bottom: 100px">
        </div>
        <div>
            <img src="images/run1.png" style="padding-top:20px;padding-bottom: 20px" width="1280" height="720">
        </div>
        <div>
            <img src="images/run2.png" style="padding-top:20px;padding-bottom: 20px">
        </div>
        <div>
            <img src="images/run3.png" style="padding-top:20px;padding-bottom: 20px">
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="container">
    <header class="site-header">
        <image src="/images/logo.png" width="350" height="100">
            <nav>
            <span class="menu">
            <ul>
                <li><a><%= link_to "Home" , home_path %> </a></li>
                <% if current_user %>
                    
                    
                <% else %>
                    <li><a><%= link_to "Sign Up", signup_path %></li></a>
                    <li><a><%= link_to "Log In", login_path %></li></a>
                <% end %>
                <li><a><%= link_to "About" , about_path %></a></li>
                
                <% if current_user %>
                    <li><a><%= link_to "Log Out", logout_path %></li></a>
                    <li><a><%= link_to "Edit", edit_user_path(current_user) %></li></a>
                    Logged in as <%= current_user.email %>.
                    
                <% end %>
            </ul>
        </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
            <p id="notice"><%= notice %></p>

            <p>
              <strong>Email:</strong>
              <%= @user.email %>
            </p>
            
            <%= link_to 'Edit', edit_user_path(@user) %> |
            <%= link_to 'Back', root_path %>
            
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>

app/views/welcome/about.html.erb
<div class="container">
    <header class="site-header">
        <image src="images/logo.png" width="350" height="100">
            <nav>
            <span class="menu">
            <ul>
                <li><a><%= link_to "Home" , home_path %> </a></li>
                <% if current_user %>
                    
                    
                <% else %>
                    <li><a><%= link_to "Sign Up", signup_path %></li></a>
                    <li><a><%= link_to "Log In", login_path %></li></a>
                <% end %>
                <li><a><%= link_to "About" , about_path %></a></li>
                
                <% if current_user %>
                    <li><a><%= link_to "Log Out", logout_path %></li></a>
                    Logged in as <%= current_user.email %>.
                    
                <% end %>
            </ul>
        </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Team Member</p>
            </header>
            <article>
                <p style="text-align: center;"><b>Auttaphol Thongvicit 5810613256</b></p>
                <p style="text-align: center;"><b>Tuchdech Jirabunyadech 5910613248</b></p>
                <p style="text-align: center;"><b>Boonyanut Puingyamsual 5910613305</b></p>
                <p style="text-align: center;"><b>Kittikun Kittithammo 5910613321</b></p>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Proposal</p>
            </header>
            <article>
                <center>
                    <table cellspacing="20">
                        <tr>
                            <td><img src="images/pro1.png" width="350px" height="350px"></td>
                            <td><img src="images/pro2.png" width="350px" height="350px"></td>
                        </tr>
                        <tr>
                            <td><img src="images/pro3.png" width="350px" height="350px"></td>
                            <td><img src="images/pro4.png" width="350px" height="350px"></td>
                        </tr>
                    </table>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">User Stories</p>
            </header>
            <article>
                <img src="images/story1.png" width="500px" height="400px">
                <img src="images/story2.png" width="500px" height="400px">
                <img src="images/story3.png" width="500px" height="400px">
                <img src="images/story4.png" width="500px" height="400px">
                <img src="images/story5.png" width="500px" height="400px">
                <img src="images/story6.png" width="500px" height="400px">
                <img src="images/story7.png" width="500px" height="400px">
                <img src="images/story8.png" width="500px" height="400px">
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Gitlab Repository Link</p>
            </header>
            <article>
                <center>
                    <p style="font-size: 1.2em"><a href="https://gitlab.com/5910613248/24preorder.git">https://gitlab.com/5910613248/24preorder.git</a></p>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Pivotal Tracker Link</p>
            </header>
            <article>
                <center>
                    <p style="font-size: 1.2em"><a href="https://www.pivotaltracker.com/projects/2407283">https://www.pivotaltracker.com/projects/2407283</a></p>
                </center>
            </article>
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>

app/views/welcome/home.html.erb
<div class="container">
    <header class="site-header">
        <image src="images/logo.png" width="350" height="100">
            <nav>
                <span class="menu">
                    <ul>
                        <li><a><%= link_to "Home" , home_path %> </a></li>
                        <% if current_user %>
                            
                            
                        <% else %>
                            <li><a><%= link_to "Sign Up", signup_path %></li></a>
                            <li><a><%= link_to "Log In", login_path %></li></a>
                        <% end %>
                        <li><a><%= link_to "About" , about_path %></a></li>
                        
                        <% if current_user %>
                            <li><a><%= link_to "Log Out", logout_path %></li></a>
                            <%= link_to 'Edit', edit_user_path(@user) %> |
                            Logged in as <%= current_user.email %>.
                            
                        <% end %>
                    </ul>
                </span>
            </nav>
    </header>
    <div class="site-main">
        <div>
            <img src="images/maintain.jpg" style="padding-top:100px;padding-bottom: 100px">
        </div>
        <div>
            <img src="images/run1.png" style="padding-top:20px;padding-bottom: 20px" width="1280" height="720">
        </div>
        <div>
            <img src="images/run2.png" style="padding-top:20px;padding-bottom: 20px">
        </div>
        <div>
            <img src="images/run3.png" style="padding-top:20px;padding-bottom: 20px">
        </div>
    </div>
    <footer class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </footer>
</div>